<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Phase0.LanguageFSharp</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KeelMatrix.Phase0.CompilerExtensionLanguages" />
    <PackageReference Include="KeelMatrix.Phase0.ContentInjectionLanguages" />
  </ItemGroup>
</Project>
